name: beacon_app
description: "P2P Emergency Communication Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Database
  sqflite_sqlcipher: ^3.1.0+1
  path: ^1.8.3
  flutter_secure_storage: ^9.0.0

  # Audio Services
  flutter_tts: ^4.0.2
  speech_to_text: ^7.3.0
  flutter_local_notifications: ^17.1.0

  # Networking
  flutter_p2p_connection: ^3.0.3

  # Utilities
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
